---
title: "Lab 2: Multiplexed 7-Segment Display"
description: "Welcome to my Quarto portfolio"
author: "Ket Hollingsworth"
date: "8/23/24"
categories:
  - labreport
draft: false
---

## Notes:
We are implementing a time-multiplexing scheme to drive two seven-segment dispalys with a single set of FPGA I/O pins.

Using a DIP switch and four other input pins (possibly connected to a DIP switch on a breadboard) to provide the data for two hexadecimal numbers. You must use a single sevent-segment decoder HDL module to drive the cathodes for both digits on the display, which therefore must be wired for multiplexed operation. Also, display the sum of the numbers on five LEDs. The seven segment display should be oriented to display the numbers upright to the viewer.

### How to multiplex:
- A convenient way to control which half is active is to turn ON the common anode of only one display at a time. The anode required substantial current, more than an FPGA output pin can drive. You can use a transistor to drive the large current.
  - lab has stock of 2N3906 PNP transistors suitable for this purpose. Be sure to limit the base current so that you don't draw too much current from the FPGA pin and choose a suitable switching speed. If you switch too slowly, your eye will notice the flicker. If you switch too fast for the electronics, the two digits will bleed together.

### Hints:
 Look at your RTL schematic in your synthesis tool (Tools -> Netlist Analyzer). Understand why your code produces the hardware you see. Be sure your combinational logic doesn’t have any registers. Be sure your logic has no latches or tristate buffers. The oscilloscope is handy for tracking down timing problems.